/**
 * 실제 시스템 다이어그램에서 노드 텍스트(부분 일치) → 핸드북 문서 경로 매핑.
 * 다이어그램 렌더 후 해당 텍스트를 가진 노드를 클릭하면 연결된 개념 문서로 이동합니다.
 */
export const REAL_SYSTEM_DIAGRAM_LINKS: Record<string, string> = {
  // ---- 1. Networking Fundamentals ----
  "IP / CIDR / Subnet": "/handbook/core-cs/ip-cidr-subnetting",
  "IP / CIDR / Subnetting": "/handbook/core-cs/ip-cidr-subnetting",
  "IP / CIDR": "/handbook/core-cs/ip-cidr-subnetting",
  CIDR: "/handbook/core-cs/ip-cidr-subnetting",
  Subnetting: "/handbook/core-cs/ip-cidr-subnetting",
  Routing: "/handbook/core-cs/routing-table",
  "Routing Table": "/handbook/core-cs/routing-table",
  "라우팅 테이블": "/handbook/core-cs/routing-table",
  "라우팅": "/handbook/core-cs/routing-table",
  NAT: "/handbook/core-cs/nat",
  "NAT 개념": "/handbook/core-cs/nat",
  "NAT GW": "/handbook/core-cs/nat",
  DNS: "/handbook/core-cs/dns-resolver-vs-authoritative",
  "DNS Resolver": "/handbook/core-cs/dns-resolver-vs-authoritative",
  "TCP / UDP": "/handbook/core-cs/tcp-vs-udp",
  "TCP vs UDP": "/handbook/core-cs/tcp-vs-udp",
  "TCP/UDP": "/handbook/core-cs/tcp-vs-udp",
  "HTTP / TLS": "/handbook/core-cs/http-https-tls",
  "HTTP / HTTPS / TLS": "/handbook/core-cs/http-https-tls",
  TLS: "/handbook/core-cs/http-https-tls",
  "L7 LB": "/handbook/core-cs/l4-vs-l7-lb",
  "L4 LB": "/handbook/core-cs/l4-vs-l7-lb",
  "L4 vs L7": "/handbook/core-cs/l4-vs-l7-lb",
  "L7 Load Balancer": "/handbook/core-cs/l4-vs-l7-lb",
  VPC: "/handbook/aws-common/public-private-subnet",
  "서브넷": "/handbook/core-cs/ip-cidr-subnetting",

  // ---- 2. Data & Storage Fundamentals ----
  Block: "/handbook/core-cs/block-file-object",
  File: "/handbook/core-cs/block-file-object",
  Object: "/handbook/core-cs/block-file-object",
  "Latency / Throughput / IOPS": "/handbook/core-cs/latency-throughput-iops",
  "ACID / 트랜잭션 / 락": "/handbook/core-cs/acid-transaction-lock",
  ACID: "/handbook/core-cs/acid-transaction-lock",
  "트랜잭션": "/handbook/core-cs/acid-transaction-lock",
  Index: "/handbook/core-cs/index-why-fast",
  "Cache hit/miss": "/handbook/core-cs/caching",
  "Cache hit/miss, TTL": "/handbook/core-cs/caching",
  "캐시 원리": "/handbook/core-cs/caching",

  // ---- 3. Distributed Systems Essentials ----
  "Stateless vs Stateful": "/handbook/core-cs/stateless-stateful",
  Stateless: "/handbook/core-cs/stateless-stateful",
  Stateful: "/handbook/core-cs/stateless-stateful",
  "Scale-up": "/handbook/core-cs/scale-up-scale-out",
  "Scale-out": "/handbook/core-cs/scale-up-scale-out",
  "Scale-up vs Scale-out": "/handbook/core-cs/scale-up-scale-out",
  "Consistency Model": "/handbook/core-cs/consistency-model",
  "일관성 모델": "/handbook/core-cs/consistency-model",
  Consistency: "/handbook/core-cs/consistency-model",
  "Queue vs Pub/Sub": "/handbook/core-cs/queue-vs-pubsub",
  Queue: "/handbook/core-cs/queue-vs-pubsub",
  "Pub/Sub": "/handbook/core-cs/queue-vs-pubsub",
  "Pub-Sub": "/handbook/core-cs/queue-vs-pubsub",
  Idempotency: "/handbook/core-cs/idempotency",
  CAP: "/handbook/core-cs/cap-theorem",
  "CAP Theorem": "/handbook/core-cs/cap-theorem",
  "분산 TX · 분산 락": "/handbook/core-cs/distributed-transaction-lock",
  "분산 TX": "/handbook/core-cs/distributed-transaction-lock",
  "분산 락": "/handbook/core-cs/distributed-transaction-lock",
  "Event-driven Architecture": "/handbook/core-cs/event-driven-arch",
  "Event-driven": "/handbook/core-cs/event-driven-arch",

  // ---- 4. Security Basics ----
  Authn: "/handbook/core-cs/authn-vs-authz",
  Authz: "/handbook/core-cs/authn-vs-authz",
  "Authentication vs Authorization": "/handbook/core-cs/authn-vs-authz",
  Authentication: "/handbook/core-cs/authn-vs-authz",
  Authorization: "/handbook/core-cs/authn-vs-authz",
  "Hash vs Encryption": "/handbook/core-cs/hash-vs-encryption",
  Hash: "/handbook/core-cs/hash-vs-encryption",
  "Symmetric / Asymmetric": "/handbook/core-cs/hash-vs-encryption",
  "Symmetric vs Asymmetric": "/handbook/core-cs/hash-vs-encryption",
  Symmetric: "/handbook/core-cs/hash-vs-encryption",
  Asymmetric: "/handbook/core-cs/hash-vs-encryption",
  "Least Privilege": "/handbook/core-cs/least-privilege",
  "Principle of Least Privilege": "/handbook/core-cs/least-privilege",
  "인바운드/아웃바운드": "/handbook/core-cs/firewall",
  "Firewall 개념": "/handbook/core-cs/firewall",
  Firewall: "/handbook/core-cs/firewall",

  // ---- 5. Reliability & Operations ----
  "Logs / Metrics / Traces": "/handbook/core-cs/observability",
  Observability: "/handbook/core-cs/observability",
  "Retry / Backoff / Jitter": "/handbook/core-cs/retry-backoff",
  "Retry / Backoff": "/handbook/core-cs/retry-backoff",
  "Retry/Backoff": "/handbook/core-cs/retry-backoff",
  "Throttling / Rate limit": "/handbook/core-cs/throttling-rate-limiting",
  Throttling: "/handbook/core-cs/throttling-rate-limiting",
  "Rate limit": "/handbook/core-cs/throttling-rate-limiting",
  RPO: "/handbook/core-cs/rto-rpo",
  RTO: "/handbook/core-cs/rto-rpo",
  "RTO / RPO": "/handbook/core-cs/rto-rpo",
  "HA / active-active": "/handbook/core-cs/ha-design",
  "HA 설계 원칙": "/handbook/core-cs/ha-design",
  "HA 설계": "/handbook/core-cs/ha-design",
  "고가용성": "/handbook/core-cs/ha-design",
  "가용 영역": "/handbook/core-cs/ha-design",
  "SLI / SLO": "/handbook/core-cs/sli-slo",
  "SLI/SLO": "/handbook/core-cs/sli-slo",
  "SLI / SLO 개념": "/handbook/core-cs/sli-slo",
  Alarm: "/handbook/core-cs/sli-slo",
  "알람": "/handbook/core-cs/sli-slo",
  "백업": "/handbook/core-cs/rto-rpo",

  // ---- 6. Containers & Orchestration (구체적 노드 우선: 이미지/런타임이 Container·컨테이너보다 먼저 매칭되도록) ----
  "컨테이너 이미지": "/handbook/core-cs/container-image",
  "Container Image": "/handbook/core-cs/container-image",
  "Container Runtime": "/handbook/core-cs/container-runtime",
  "이미지 레지스트리": "/handbook/core-cs/container-registry",
  "서비스 엔드포인트": "/handbook/core-cs/container-service-endpoint",
  "Service Endpoint": "/handbook/core-cs/container-service-endpoint",
  오케스트레이터: "/handbook/core-cs/container-runtime",
  "Container Orchestration": "/handbook/core-cs/container-runtime",
};
