/**
 * 실제 시스템 다이어그램에서 노드 텍스트(부분 일치) → 핸드북 문서 경로 매핑.
 * 다이어그램 렌더 후 해당 텍스트를 가진 노드를 클릭하면 연결된 개념 문서로 이동합니다.
 */
export const REAL_SYSTEM_DIAGRAM_LINKS: Record<string, string> = {
  // ---- 네트워크 ----
  "IP / CIDR / Subnetting": "/handbook/core-cs/ip-cidr-subnetting",
  "IP / CIDR": "/handbook/core-cs/ip-cidr-subnetting",
  CIDR: "/handbook/core-cs/ip-cidr-subnetting",
  Subnetting: "/handbook/core-cs/ip-cidr-subnetting",
  "Routing Table": "/handbook/core-cs/routing-table",
  "라우팅 테이블": "/handbook/core-cs/routing-table",
  "라우팅": "/handbook/core-cs/routing-table",
  "NAT 개념": "/handbook/core-cs/nat",
  "NAT GW": "/handbook/core-cs/nat",
  NAT: "/handbook/core-cs/nat",
  "DNS Resolver": "/handbook/core-cs/dns-resolver-vs-authoritative",
  DNS: "/handbook/core-cs/dns-resolver-vs-authoritative",
  "TCP vs UDP": "/handbook/core-cs/tcp-vs-udp",
  "TCP/UDP": "/handbook/core-cs/tcp-vs-udp",
  "HTTP / HTTPS / TLS": "/handbook/core-cs/http-https-tls",
  TLS: "/handbook/core-cs/http-https-tls",
  "L4 vs L7": "/handbook/core-cs/l4-vs-l7-lb",
  "L7 LB": "/handbook/core-cs/l4-vs-l7-lb",
  "L4 LB": "/handbook/core-cs/l4-vs-l7-lb",
  "L7 Load Balancer": "/handbook/core-cs/l4-vs-l7-lb",
  VPC: "/handbook/aws-common/public-private-subnet",
  "서브넷": "/handbook/core-cs/ip-cidr-subnetting",

  // ---- 분산 시스템 ----
  "Stateless vs Stateful": "/handbook/core-cs/stateless-stateful",
  Stateless: "/handbook/core-cs/stateless-stateful",
  Stateful: "/handbook/core-cs/stateless-stateful",
  "Scale-up vs Scale-out": "/handbook/core-cs/scale-up-scale-out",
  "Scale-up": "/handbook/core-cs/scale-up-scale-out",
  "Scale-out": "/handbook/core-cs/scale-up-scale-out",
  "CAP Theorem": "/handbook/core-cs/cap-theorem",
  CAP: "/handbook/core-cs/cap-theorem",
  "Consistency Model": "/handbook/core-cs/consistency-model",
  "일관성 모델": "/handbook/core-cs/consistency-model",
  Consistency: "/handbook/core-cs/consistency-model",
  Idempotency: "/handbook/core-cs/idempotency",
  "Retry / Backoff": "/handbook/core-cs/retry-backoff",
  "Retry/Backoff": "/handbook/core-cs/retry-backoff",
  "Queue vs Pub/Sub": "/handbook/core-cs/queue-vs-pubsub",
  Queue: "/handbook/core-cs/queue-vs-pubsub",
  "Pub-Sub": "/handbook/core-cs/queue-vs-pubsub",
  "Event-driven Architecture": "/handbook/core-cs/event-driven-arch",
  "Event-driven": "/handbook/core-cs/event-driven-arch",

  // ---- 보안 기본 ----
  "Authentication vs Authorization": "/handbook/core-cs/authn-vs-authz",
  Authentication: "/handbook/core-cs/authn-vs-authz",
  Authorization: "/handbook/core-cs/authn-vs-authz",
  "Hash vs Encryption": "/handbook/core-cs/hash-vs-encryption",
  Hash: "/handbook/core-cs/hash-vs-encryption",
  "Symmetric vs Asymmetric": "/handbook/core-cs/hash-vs-encryption",
  Symmetric: "/handbook/core-cs/hash-vs-encryption",
  Asymmetric: "/handbook/core-cs/hash-vs-encryption",
  "Principle of Least Privilege": "/handbook/core-cs/least-privilege",
  "Least Privilege": "/handbook/core-cs/least-privilege",
  "Firewall 개념": "/handbook/core-cs/firewall",
  Firewall: "/handbook/core-cs/firewall",

  // ---- 운영 & 신뢰성 ----
  "RTO / RPO": "/handbook/core-cs/rto-rpo",
  RPO: "/handbook/core-cs/rto-rpo",
  RTO: "/handbook/core-cs/rto-rpo",
  "HA 설계 원칙": "/handbook/core-cs/ha-design",
  "HA 설계": "/handbook/core-cs/ha-design",
  "고가용성": "/handbook/core-cs/ha-design",
  "가용 영역": "/handbook/core-cs/ha-design",
  "Observability": "/handbook/core-cs/observability",
  "Logs / Metrics / Traces": "/handbook/core-cs/observability",
  "SLI / SLO 개념": "/handbook/core-cs/sli-slo",
  "SLI / SLO": "/handbook/core-cs/sli-slo",
  "SLI/SLO": "/handbook/core-cs/sli-slo",
  Alarm: "/handbook/core-cs/sli-slo",
  "알람": "/handbook/core-cs/sli-slo",
  "캐시 원리": "/handbook/core-cs/caching",
  "백업": "/handbook/core-cs/rto-rpo",
};
